### ISSUE TITLE
Running `make run` results in failure due to external images not being available.

### ISSUE THREAD

**Issue by Perseverance** [0xPolygonHermez/zkevm-node#1175]
## Description
Hi team. Trying to run the node locally results in failure as `hermeznetwork/geth-zkevm-contracts` is either not available or not publicly accessibly anymore. Here is simplified stacktrace by just running the docker-compose up for zkevm-mock-l1-network.

```
georgespasov@Georges-MacBook-Pro zkevm-node % docker-compose -f docker-compose.yml up -d zkevm-mock-l1-network
WARNING: The CONFIG_MODE variable is not set. Defaulting to a blank string.
Pulling zkevm-mock-l1-network (hermeznetwork/geth-zkevm-contracts@sha256:b88d03a42ef4975d0b92c0dd192e1bf4d673fc4b761aaf4bcfdd606989c1b006)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling zkevm-mock-l1-network (hermeznetwork/geth-zkevm-contracts@sha256:b88d03a42ef4975d0b92c0dd192e1bf4d673fc4b761aaf4bcfdd606989c1b006)...
ERROR: pull access denied for hermeznetwork/geth-zkevm-contracts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Update 1: Same behaviour is experienced after fix of geth-zkevm-contracts with the prover
```
docker-compose -f docker-compose.yml up -d zkevm-prover
WARNING: The CONFIG_MODE variable is not set. Defaulting to a blank string.
Pulling zkevm-prover (hermeznetwork/zkevm-prover:develop@sha256:367da8c2e4b90aec1b212bb7da9f6b7f7005241ba522345dd4504914a0b49886)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling zkevm-prover (hermeznetwork/zkevm-prover:develop@sha256:367da8c2e4b90aec1b212bb7da9f6b7f7005241ba522345dd4504914a0b49886)...
ERROR: pull access denied for hermeznetwork/zkevm-prover, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

## Possible solutions
- Make the zkevm-contracts image publicly available
- Add to the docs how to build a local version of the geth-zkevm-contracts image

**Comment by Perseverance** [comment]
I've updated the issue with a new issue concerning the building of the executor. However I cannot completely solve this issue until https://github.com/0xPolygonHermez/zkevm-prover/issues/97 is solved. Im glad to help :)

**Comment by arnaubennassar** [comment]
Images have been opened since you open this issue, so it shouldn't be a problem anymore :D

**Comment by Perseverance** [comment]
Thanks @arnaubennassar . Can you please review the PR that creates docker image for the prover for arm architecture too?

**Comment by BruninhoLumx** [comment]
I'm still having this issue: 
```

Continue with the new image? [yN]y 
Pulling zkevm-approve (zkevm-node:)...
ERROR: pull access denied for zkevm-node, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Even with after running docker login, I'm still having this problem.

**Comment by defidegenerate** [comment]
this happened to me just now as well.  @BruninhoLumx did you do something, or did it end up just fixing itself?

**Comment by defidegenerate** [comment]
if anyone else stumbles on this, it was a transient issue.  When I re-ran `make build-docker` and then `make run` everything worked fine.
